-- app_user
create table if not exists app_user
(
    id bigint generated by default as identity
    constraint app_user_pkey
    primary key,
    creation_date_time timestamp,
    email varchar(255) not null
    constraint uk_1j9d9a06i600gd43uu3km82jw
    unique,
    name varchar(255) not null,
    password varchar(255) not null,
    photo varchar(255)
    );

alter table app_user owner to postgres;

insert into app_user (creation_date_time, email, name, password, photo)
values (now(), 'ania@op.pl', 'Ania', '$2y$10$GH1ha1kr8wTEXICd24Z.Ku85wd2rzaUQHjDkIV8HqmVm9ALtNbKAy', null),
       (now(), 'ola@op.pl', 'Ola', '$2y$10$JAFUreeGn/ecgMX7xPlRPeKAlaEbCTisCzEtqgJT5bPxPKqw7OScu', 'https://www.colorland.pl/sites/default/files/article-image/kot1_1.jpg'),
       (now(), 'ala@op.pl', 'Ala', '$2y$10$hWQdnU0KP1kdpApuA7OtsuEjxA817u3iOuOYnqDg4gq3u605pd9Qe', 'https://www.odkrywamyzakryte.com/wp-content/uploads/2017/05/56999502_l.jpg'),
       (now(), 'tomek@op.pl', 'Tomek', '$2y$10$ZHCRzNP.YqQ8BGekmHSEq.xuWZrtPVC0dUoWwo13ph/0/Q0ooAk72', 'https://czasnamarketing.pl/wp-content/uploads/2019/02/key1-1024x623.jpg'),
       (now(), 'arek@op.pl', 'Arek', '$2y$10$D.tqzy0fvMwUTVeKEVdBcOU3Pzr26cRnGpEwqhQu.bbw0FRkZad9m', 'https://www.mypolacy.de/files/avatars/5d07af463c57b841310441a7_fb-1560784710981.jpg'),
       (now(), 'kamil@op.pl', 'Kamil', '$2y$10$y1NwrKTPyqUFgt7WdUvDMuVi6.AoevUvs9VpSfghs41KBad6VbJZS', 'https://www.mypolacy.de/files/avatars/5dd51b7a9444ec3974489816_fb-1574247291388.jpg'),
       (now(), 'magda@op.pl', 'Magda', '$2y$10$pOg7jcCb5DXyjVRZgK/7w.uZWg.NHEqhLm.sQaF4GjRWX.3f5Z4Aq', 'https://www.foto4u.pl/blog/artykul/!uploads/profilowe/profesjonalne.jpg'),
       (now(), 'piotr@op.pl', 'Piotr', '$2y$10$Aj3ihtdMJp8Zl7kDkqWITehEdoNgJ.kw51KDRto1LqwTbVeSvHUE.', 'https://lh3.googleusercontent.com/proxy/nnRJ2-EecMAebNzhTH1jkAFHT5LYoZF-1d3-7BVTNV3zUhAajvYYmC1gC6Gubo6Fqd8xy_9iTlXSnk_runxprPpcP9InyR1Avow7qyv1UWxMWyXPCnxsVvL-HnpgjomfscxoOsSSV3SW9jUNMsGZBRoW5snbiYCK9Fmg0TE06qdasLpXfwusHh8MWTqofJyWjuVENAGqEP4XaeIB5SfP'),
       (now(), 'marta@op.pl', 'Marta', '$2y$10$icA1uwRcPc43R6rsj6G.OeZiBwv49u5cSGj9cb1VEwvN2Y65tK8ja', 'https://i0.wp.com/karieranaobcasach.com/wp-content/uploads/2020/04/Zdjecie-profilowe.png?fit=560%2C315&ssl=1'),
       (now(), 'adrian@op.pl', 'Adrian', '$2y$10$IJNIGL4HY3PWrnIquGoEwOHJJ/MFbpWxe7MV7XPD.Ntfm5LIIYOcC', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX512qexq3hickX7mPlf2OvC16YPjXtjDDnA&usqp=CAU'),
       (now(), 'bogdan@op.pl', 'Bogdan', '$2y$10$hU4qxykFflulaTMLYPaEHuturEkyBOU1FP05kpC6X4CnW0NGR/C56', 'https://i.redd.it/a9q2jze2m0a41.jpg');


-- user_friend
create table if not exists user_friend
(
    friend_id bigint not null
    constraint fkpsck89bgkoa8f0dwbq9p8pbsc
    references app_user,
    user_id bigint not null
    constraint fklsegpybcpjyn5sjukct036js0
    references app_user,
    date timestamp,
    constraint user_friend_pkey
    primary key (friend_id, user_id)
    );

alter table user_friend owner to postgres;

INSERT INTO user_friend (friend_id, user_id, date)
VALUES (4, 2, now()),
       (7, 2, now()),
       (8, 2, now()),
       (3, 1, now()),
       (2, 1, now()),
       (8, 1, now()),
       (11, 1, now()),
       (10, 1, now()),
       (1, 3, now()),
       (9, 3, now()),
       (8, 3, now()),
       (4, 3, now()),
       (2, 3, now()),
       (1, 4, now()),
       (2, 4, now()),
       (6, 4, now()),
       (5, 4, now()),
       (11, 4, now()),
       (8, 4, now()),
       (9, 4, now()),
       (2, 5, now()),
       (4, 5, now()),
       (3, 5, now()),
       (6, 5, now()),
       (10, 5, now()),
       (7, 5, now()),
       (2, 6, now()),
       (1, 6, now()),
       (11, 6, now()),
       (2, 7, now()),
       (3, 7, now()),
       (1, 7, now()),
       (9, 7, now()),
       (5, 7, now()),
       (10, 7, now()),
       (10, 8, now()),
       (2, 8, now()),
       (7, 8, now()),
       (7, 9, now()),
       (1, 9, now()),
       (4, 9, now()),
       (5, 9, now()),
       (11, 9, now()),
       (7, 10, now()),
       (1, 10, now()),
       (2, 10, now()),
       (4, 10, now()),
       (5, 10, now()),
       (8, 10, now()),
       (9, 10, now()),
       (11, 10, now()),
       (7, 11, now()),
       (3, 11, now()),
       (4, 11, now()),
       (8, 11, now());


-- server
create table if not exists server
(
    id bigint generated by default as identity
    constraint server_pkey
    primary key,
    creation_date_time timestamp,
    name varchar(255) not null,
    photo varchar(255),
    owner bigint not null
    constraint fkruougy479rbjhldtbet52yxpt
    references app_user
    );

alter table server owner to postgres;

insert into server (creation_date_time, name, photo, owner)
values (now(), 'Thor', 'https://bi.im-g.pl/im/9c/7b/15/z22526876V,Kadr-z-filmu--Thor--Ragnarok-.jpg', 1),
       (now(), 'Oslo', 'https://desenio.pl/bilder/artiklar/zoom/7837_2.jpg?imgwidth=435&qt=', 3),
       (now(), 'Apollo', 'https://ciekawamitologia.pl/images/apollo.jpg', 4),
       (now(), 'Super Mario', 'https://ocdn.eu/images/pulscms/MzQ7MDA_/1d4c2a6858e2bdebcad926d9a51f69e2.jpg', 6),
       (now(), 'Onopedia', 'https://static.wikia.nocookie.net/onopedia/images/a/a5/Kaczy%C5%84ski.jpg/revision/latest/smart/width/250/height/250?cb=20171016081303&path-prefix=pl', 7),
       (now(), 'Slugterra', 'https://cdn.hbogo.eu/images/A7949242-BA62-4FA7-94DD-EAEE30A169A7/1280_720.jpg', 10),
       (now(), 'League of Legends', 'https://lenovogaming.pl/files/Gry/2021/Free/3.jpg', 11);


-- server_user
create table if not exists server_user
(
    server_id bigint not null
    constraint fk6689vmwq0wjpd5ebp5ocnnl96
    references server,
    user_id bigint not null
    constraint fk6e6uriuy0e5ojh4evporfei9h
    references app_user,
    join_date_time timestamp,
    constraint server_user_pkey
    primary key (server_id, user_id)
    );

alter table server_user owner to postgres;

insert into server_user (server_id, user_id, join_date_time)
values (1, 1, now()),
       (1, 2, now()),
       (1, 5, now()),
       (2, 3, now()),
       (2, 2, now()),
       (2, 1, now()),
       (2, 6, now()),
       (2, 7, now()),
       (2, 8, now()),
       (2, 9, now()),
       (2, 10, now()),
       (2, 11, now()),
       (3, 4, now()),
       (3, 2, now()),
       (4, 6, now()),
       (4, 2, now()),
       (4, 1, now()),
       (5, 2, now()),
       (5, 3, now()),
       (5, 8, now()),
       (6, 10, now()),
       (6, 1, now()),
       (6, 3, now()),
       (7, 11, now()),
       (7, 1, now()),
       (7, 5, now());


-- call
create table if not exists call
(
    id bigint generated by default as identity
    constraint call_pkey
    primary key,
    attenderx double precision,
    attendery double precision,
    callerx double precision,
    callery double precision,
    end_date_time timestamp,
    start_date_time timestamp not null,
    attender bigint not null
    constraint fkgwr4cklsroq2o7wipttppa83e
    references app_user,
    caller bigint not null
    constraint fk5na8l00dkn49ylfp6ccl4xx9
    references app_user
);

alter table call owner to postgres;


-- message
create table if not exists message
(
    id bigint generated by default as identity
    constraint message_pkey
    primary key,
    content varchar(255) not null,
    date_time timestamp,
    edited boolean default false,
    sender bigint
    constraint fkjnl1hp0atnmqgu6xk3moybws3
    references app_user
    );

alter table message owner to postgres;


-- private_message
create table if not exists private_message
(
    id bigint not null
    constraint private_message_pkey
    primary key
    constraint fk5py9hmpqopws0ubbm1nchypu5
    references message,
    receiver bigint
    constraint fkr42n45rbunxw4mq5mnk15lryd
    references app_user
);

alter table private_message owner to postgres;


-- server_message
create table if not exists server_message
(
    id bigint not null
    constraint server_message_pkey
    primary key
    constraint fkjaxbgitpxsr05mpvqvy90fa5k
    references message,
    server_id bigint
    constraint fko2a2dnkh8yns5itdi4o7af898
    references server
);

alter table server_message owner to postgres;

