insert into server_user (server_id, user_id, join_date_time)
values (1, 1, now()),
       (1, 2, now()),
       (1, 5, now()),
       (2, 3, now()),
       (2, 2, now()),
       (2, 1, now()),
       (2, 6, now()),
       (2, 7, now()),
       (2, 8, now()),
       (2, 9, now()),
       (2, 10, now()),
       (2, 11, now()),
       (3, 4, now()),
       (3, 2, now()),
       (4, 6, now()),
       (4, 2, now()),
       (4, 1, now()),
       (5, 2, now()),
       (5, 3, now()),
       (5, 8, now()),
       (6, 10, now()),
       (6, 1, now()),
       (6, 3, now()),
       (7, 11, now()),
       (7, 1, now()),
       (7, 5, now());