INSERT INTO user_friend (friend_id, user_id, date)
VALUES (1, 2, now()),
       (2, 1, now()),
       (1, 3, now()),
       (3, 1, now()),
       (2, 3, now()),
       (3, 2, now()),
       (2, 5, now()),
       (5, 2, now()),
       (3, 10, now()),
       (10, 3, now()),
       (3, 8, now()),
       (8, 3, now()),
       (4, 10, now()),
       (10, 4, now()),
       (4, 8, now()),
       (8, 4, now()),
       (4, 11, now()),
       (11, 4, now()),
       (5, 6, now()),
       (6, 5, now()),
       (5, 7, now()),
       (7, 5, now()),
       (5, 1, now()),
       (1, 5, now()),
       (9, 1, now()),
       (1, 9, now());