import { StringSet } from '../contexts';

const strings: StringSet = {
  emailLabel: 'Your email address',
  emailPlaceholder: 'email@address.com',
  nickLabel: 'Your nickname',
  nickPlaceholder: 'Nickname',
  passwordLabel: 'Your password',
  passwordPlaceholder: 'Password',
  retypePasswordLabel: 'Retype password',
  retypePasswordPlaceholder: 'Password',
  register: 'Sign up',
  login: 'Sign in',
  invalidEmailLabel: 'Invalid email address',
  invalidNickLabel: 'Nick must have at least 3 characters',
  invalidPasswordLabel:
    'Password must contains 8-30 characters, 1 upper and lower letter, 1 digit and 1 special character',
  passwordsNotEqualLabel: 'Passwords are not equal',
  emailConflict: 'User with the given email already exists',
  serverError: 'Upss... Something went wrong. Try again later!',
  authenticationFailed: 'Invalid login or password',
  messagePlaceholder: 'Write a message',
  settings: 'Settings',
  language: 'Language',
  theme: 'Theme',
  selectLanguage: 'Select language',
  selectTheme: 'Select theme',
  PL: 'Polish',
  ENG: 'English',
  light: 'Light',
  dark: 'Dark',
  changeName: 'Change nick',
  changePassword: 'Change password',
  currentPassword: 'Current password',
  newName: 'New nickname',
  newPassword: 'New password',
  profile: 'Profile',
  changePhoto: 'Change photo',
  photoUrl: 'Photo url',
  signOut: 'Sign out',
};

export default strings;
