import { StringSet } from '../contexts';

const strings: StringSet = {
  emailLabel: 'Twój adres email',
  emailPlaceholder: 'email@adres.pl',
  nickLabel: 'Twoja nazwa użytkownika',
  nickPlaceholder: 'Nazwa użytkownika',
  passwordLabel: 'Hasło',
  passwordPlaceholder: 'Hasło',
  retypePasswordLabel: 'Powtórz hasło',
  retypePasswordPlaceholder: 'Hasło',
  register: 'Zarejestruj się',
  login: 'Zaloguj się',
  invalidEmailLabel: 'Nieprawidłowy adres email',
  invalidNickLabel: 'Nazwa użytkownika musi mieć co najmniej 3 znaki',
  invalidPasswordLabel:
    'Hasło musi zawierać 8-30 znaków, 1 wielką i małą literę, 1 cyfrę oraz 1 znak specjalny',
  passwordsNotEqualLabel: 'Hasła muszą być takie same',
  emailConflict: 'Użytkownik z podanym emailem już istnieje',
  serverError: 'Upss... Coś poszło nie tak. Spróbuj ponownie później!',
  authenticationFailed: 'Nieprawidłowy login lub hasło',
  messagePlaceholder: 'Napisz wiadomość',
  settings: 'Ustawienia',
  language: 'Język',
  theme: 'Motyw',
  selectLanguage: 'Wybierz język',
  selectTheme: 'Wybierz motyw',
  PL: 'Polski',
  ENG: 'Angielski',
  light: 'Jasny',
  dark: 'Ciemny',
  changeName: 'Zmień nazwę',
  changePassword: 'Zmień hasło',
  currentPassword: 'Obecne hasło',
  newName: 'Nowa nazwa',
  newPassword: 'Nowe hasło',
  profile: 'Profil',
  changePhoto: 'Zmień zdjęcie',
  photoUrl: 'Adres zdjęcia',
  signOut: 'Wyloguj się',
  failed: 'Ups... Nie udało się!',
  invalidUrl: 'Niepoprawne źródło',
  joinCodePlaceholder: 'Podaj kod serwera',
  join: 'Dołącz',
  add: 'Dodaj',
  invalidJoinCode: 'Nie znaleziono serwera z takim kodem!',
  successJoin: 'Udało się dołączyć do serwera',
  noResults: 'Brak wyników',
  findFriends: 'Szukaj przyjaciół',
  findServers: 'Szukaj serwerów',
  success: 'Wykonano pomyślnie!',
};

export default strings;
